version: '3' # hub.docker.com/_/mysql

services:
  database:
    build:
      context: ./database
    environment: 
      MYSQL_ROOT_PASSWORD: MyDatabaseLogin12
    container_name: database
    ports:
      - "3306:3306" # default port for mysql is 3306
    networks:
      - backend
  api:
    container_name: api_go
    build:
      context: ./api
    ports: 
      - "8000:8000"
    expose: 
      - "8000"
    networks: 
      - backend
      - frontend
    depends_on: 
      - database
  front-end:
    build: 
      context: ./front-end
    container_name: frontend
    ports: 
      - "4000:80"
    networks: 
      - frontend
    depends_on: 
      - database
      - api
networks: 
  backend:
  frontend: